#trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'  # Choose based on your project needs

steps:
  - checkout: self
  
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x.x'  # Adjust to match your project’s .NET version

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*.csproj'
      arguments: '--logger trx'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/*.trx'
      testRunTitle: 'Functional Tests'